name: Aperture
main: pw.valaria.aperture.ApertureCore
version: "1.1"
author: electronicboy
website: alphheimmc.enjin.com
load: STARTUP

api-version: "1.13"

depend: [Towny, Vault, LuckPerms]

permissions:
  alphheim.lores.color:
    default: op
    children:
      alphheim.lores.color.0: true
      alphheim.lores.color.1: true
      alphheim.lores.color.2: true
      alphheim.lores.color.3: true
      alphheim.lores.color.4: true
      alphheim.lores.color.5: true
      alphheim.lores.color.6: true
      alphheim.lores.color.7: true
      alphheim.lores.color.8: true
      alphheim.lores.color.9: true
      alphheim.lores.color.a: true
      alphheim.lores.color.b: true
      alphheim.lores.color.c: true
      alphheim.lores.color.d: true
      alphheim.lores.color.e: true
      alphheim.lores.color.f: true
      alphheim.lores.color.k: true
      alphheim.lores.color.m: true
      alphheim.lores.color.n: true
      alphheim.lores.color.o: true
      alphheim.lores.color.r: true
  alphheim.lores.name:
    default: op
  alphheim.lores.owner:
    default: op
  alphheim.lores.lore:
    default: op

  alphheim.owner:
    default: false
  alphheim.dev:
    default: false
  alphheim.ha:
    default: false
  alphheim.admin:
    default: false
  alphheim.mod:
    default: false

  alphheim.dwarf:
    default: false
  alphheim.elf:
    default: false
  alphheim.human:
    default: false

  alphheim.leader:
    default: false
  alphheim.royal:
    default: false
