create table warps (
    SERVER_NAME VARCHAR(32),
    WARP_NAME VARCHAR(32) NOT NULL,
    WORLD_NAME VARCHAR(32) NOT NULL,
    WORLD_UUID CHAR(36) NOT NULL,
    WARP_X DOUBLE NOT NULL,
    WARP_Y DOUBLE NOT NULL,
    WARP_Z DOUBLE NOT NULL,
    WARP_PITCH FLOAT NOT NULL,
    WARP_YAW FLOAT NOT NULL
);

CREATE INDEX IWARP_SERVER ON warps (SERVER_NAME, WARP_NAME)